camera_id: home-road
polygon:
  points:
  - - 27
    - 910
  - - 27
    - 907
  - - 1521
    - 1125
  - - 3757
    - 1350
  - - 3836
    - 1341
  - - 3832
    - 2153
  - - 15
    - 2147
  - - 26
    - 908
count_line:
  start:
  - 340
  - 793
  end:
  - 888
  - 911
  direction: BOTH
